#define DBUS_EXPORT __attribute__((visibility("default")))

DBUS_EXPORT long dbus_error_init() { return 0; }
DBUS_EXPORT long dbus_error_free() { return 0; }
DBUS_EXPORT long dbus_set_error() { return 0; }
DBUS_EXPORT long dbus_set_error_const() { return 0; }
DBUS_EXPORT long dbus_move_error() { return 0; }
DBUS_EXPORT long dbus_error_has_name() { return 0; }
DBUS_EXPORT long dbus_error_is_set() { return 0; }
DBUS_EXPORT long dbus_parse_address() { return 0; }
DBUS_EXPORT long dbus_address_entry_get_value() { return 0; }
DBUS_EXPORT long dbus_address_entry_get_method() { return 0; }
DBUS_EXPORT long dbus_address_entries_free() { return 0; }
DBUS_EXPORT long dbus_address_escape_value() { return 0; }
DBUS_EXPORT long dbus_address_unescape_value() { return 0; }
DBUS_EXPORT long dbus_malloc() { return 0; }
DBUS_EXPORT long dbus_malloc0() { return 0; }
DBUS_EXPORT long dbus_realloc() { return 0; }
DBUS_EXPORT long dbus_free() { return 0; }
DBUS_EXPORT long dbus_free_string_array() { return 0; }
DBUS_EXPORT long dbus_shutdown() { return 0; }
DBUS_EXPORT long dbus_message_new() { return 0; }
DBUS_EXPORT long dbus_message_new_method_call() { return 0; }
DBUS_EXPORT long dbus_message_new_method_return() { return 0; }
DBUS_EXPORT long dbus_message_new_signal() { return 0; }
DBUS_EXPORT long dbus_message_new_error() { return 0; }
DBUS_EXPORT long dbus_message_new_error_printf() { return 0; }
DBUS_EXPORT long dbus_message_copy() { return 0; }
DBUS_EXPORT long dbus_message_ref() { return 0; }
DBUS_EXPORT long dbus_message_unref() { return 0; }
DBUS_EXPORT long dbus_message_get_type() { return 0; }
DBUS_EXPORT long dbus_message_set_path() { return 0; }
DBUS_EXPORT long dbus_message_get_path() { return 0; }
DBUS_EXPORT long dbus_message_has_path() { return 0; }
DBUS_EXPORT long dbus_message_set_interface() { return 0; }
DBUS_EXPORT long dbus_message_get_interface() { return 0; }
DBUS_EXPORT long dbus_message_has_interface() { return 0; }
DBUS_EXPORT long dbus_message_set_member() { return 0; }
DBUS_EXPORT long dbus_message_get_member() { return 0; }
DBUS_EXPORT long dbus_message_has_member() { return 0; }
DBUS_EXPORT long dbus_message_set_error_name() { return 0; }
DBUS_EXPORT long dbus_message_get_error_name() { return 0; }
DBUS_EXPORT long dbus_message_set_destination() { return 0; }
DBUS_EXPORT long dbus_message_get_destination() { return 0; }
DBUS_EXPORT long dbus_message_set_sender() { return 0; }
DBUS_EXPORT long dbus_message_get_sender() { return 0; }
DBUS_EXPORT long dbus_message_get_signature() { return 0; }
DBUS_EXPORT long dbus_message_set_no_reply() { return 0; }
DBUS_EXPORT long dbus_message_get_no_reply() { return 0; }
DBUS_EXPORT long dbus_message_is_method_call() { return 0; }
DBUS_EXPORT long dbus_message_is_signal() { return 0; }
DBUS_EXPORT long dbus_message_is_error() { return 0; }
DBUS_EXPORT long dbus_message_has_destination() { return 0; }
DBUS_EXPORT long dbus_message_has_sender() { return 0; }
DBUS_EXPORT long dbus_message_has_signature() { return 0; }
DBUS_EXPORT long dbus_message_get_serial() { return 0; }
DBUS_EXPORT long dbus_message_set_serial() { return 0; }
DBUS_EXPORT long dbus_message_set_reply_serial() { return 0; }
DBUS_EXPORT long dbus_message_get_reply_serial() { return 0; }
DBUS_EXPORT long dbus_message_set_auto_start() { return 0; }
DBUS_EXPORT long dbus_message_get_auto_start() { return 0; }
DBUS_EXPORT long dbus_message_get_path_decomposed() { return 0; }
DBUS_EXPORT long dbus_message_append_args() { return 0; }
DBUS_EXPORT long dbus_message_append_args_valist() { return 0; }
DBUS_EXPORT long dbus_message_get_args() { return 0; }
DBUS_EXPORT long dbus_message_get_args_valist() { return 0; }
DBUS_EXPORT long dbus_message_contains_unix_fds() { return 0; }
DBUS_EXPORT long dbus_message_iter_init_closed() { return 0; }
DBUS_EXPORT long dbus_message_iter_init() { return 0; }
DBUS_EXPORT long dbus_message_iter_has_next() { return 0; }
DBUS_EXPORT long dbus_message_iter_next() { return 0; }
DBUS_EXPORT long dbus_message_iter_get_signature() { return 0; }
DBUS_EXPORT long dbus_message_iter_get_arg_type() { return 0; }
DBUS_EXPORT long dbus_message_iter_get_element_type() { return 0; }
DBUS_EXPORT long dbus_message_iter_recurse() { return 0; }
DBUS_EXPORT long dbus_message_iter_get_basic() { return 0; }
DBUS_EXPORT long dbus_message_iter_get_element_count() { return 0; }
DBUS_EXPORT long dbus_message_iter_get_array_len() { return 0; }
DBUS_EXPORT long dbus_message_iter_get_fixed_array() { return 0; }
DBUS_EXPORT long dbus_message_iter_init_append() { return 0; }
DBUS_EXPORT long dbus_message_iter_append_basic() { return 0; }
DBUS_EXPORT long dbus_message_iter_append_fixed_array() { return 0; }
DBUS_EXPORT long dbus_message_iter_open_container() { return 0; }
DBUS_EXPORT long dbus_message_iter_close_container() { return 0; }
DBUS_EXPORT long dbus_message_iter_abandon_container() { return 0; }
DBUS_EXPORT long dbus_message_iter_abandon_container_if_open() { return 0; }
DBUS_EXPORT long dbus_message_lock() { return 0; }
DBUS_EXPORT long dbus_set_error_from_message() { return 0; }
DBUS_EXPORT long dbus_message_allocate_data_slot() { return 0; }
DBUS_EXPORT long dbus_message_free_data_slot() { return 0; }
DBUS_EXPORT long dbus_message_set_data() { return 0; }
DBUS_EXPORT long dbus_message_get_data() { return 0; }
DBUS_EXPORT long dbus_message_type_from_string() { return 0; }
DBUS_EXPORT long dbus_message_type_to_string() { return 0; }
DBUS_EXPORT long dbus_message_marshal() { return 0; }
DBUS_EXPORT long dbus_message_demarshal() { return 0; }
DBUS_EXPORT long dbus_message_demarshal_bytes_needed() { return 0; }
DBUS_EXPORT long dbus_message_set_allow_interactive_authorization() { return 0; }
DBUS_EXPORT long dbus_message_get_allow_interactive_authorization() { return 0; }
DBUS_EXPORT long dbus_connection_open() { return 0; }
DBUS_EXPORT long dbus_connection_open_private() { return 0; }
DBUS_EXPORT long dbus_connection_ref() { return 0; }
DBUS_EXPORT long dbus_connection_unref() { return 0; }
DBUS_EXPORT long dbus_connection_close() { return 0; }
DBUS_EXPORT long dbus_connection_get_is_connected() { return 0; }
DBUS_EXPORT long dbus_connection_get_is_authenticated() { return 0; }
DBUS_EXPORT long dbus_connection_get_is_anonymous() { return 0; }
DBUS_EXPORT long dbus_connection_get_server_id() { return 0; }
DBUS_EXPORT long dbus_connection_can_send_type() { return 0; }
DBUS_EXPORT long dbus_connection_set_exit_on_disconnect() { return 0; }
DBUS_EXPORT long dbus_connection_flush() { return 0; }
DBUS_EXPORT long dbus_connection_read_write_dispatch() { return 0; }
DBUS_EXPORT long dbus_connection_read_write() { return 0; }
DBUS_EXPORT long dbus_connection_borrow_message() { return 0; }
DBUS_EXPORT long dbus_connection_return_message() { return 0; }
DBUS_EXPORT long dbus_connection_steal_borrowed_message() { return 0; }
DBUS_EXPORT long dbus_connection_pop_message() { return 0; }
DBUS_EXPORT long dbus_connection_get_dispatch_status() { return 0; }
DBUS_EXPORT long dbus_connection_dispatch() { return 0; }
DBUS_EXPORT long dbus_connection_has_messages_to_send() { return 0; }
DBUS_EXPORT long dbus_connection_send() { return 0; }
DBUS_EXPORT long dbus_connection_send_with_reply() { return 0; }
DBUS_EXPORT long dbus_connection_send_with_reply_and_block() { return 0; }
DBUS_EXPORT long dbus_connection_set_watch_functions() { return 0; }
DBUS_EXPORT long dbus_connection_set_timeout_functions() { return 0; }
DBUS_EXPORT long dbus_connection_set_wakeup_main_function() { return 0; }
DBUS_EXPORT long dbus_connection_set_dispatch_status_function() { return 0; }
DBUS_EXPORT long dbus_connection_get_unix_user() { return 0; }
DBUS_EXPORT long dbus_connection_get_unix_process_id() { return 0; }
DBUS_EXPORT long dbus_connection_get_adt_audit_session_data() { return 0; }
DBUS_EXPORT long dbus_connection_set_unix_user_function() { return 0; }
DBUS_EXPORT long dbus_connection_get_windows_user() { return 0; }
DBUS_EXPORT long dbus_connection_set_windows_user_function() { return 0; }
DBUS_EXPORT long dbus_connection_set_allow_anonymous() { return 0; }
DBUS_EXPORT long dbus_connection_set_route_peer_messages() { return 0; }
DBUS_EXPORT long dbus_connection_add_filter() { return 0; }
DBUS_EXPORT long dbus_connection_remove_filter() { return 0; }
DBUS_EXPORT long dbus_connection_allocate_data_slot() { return 0; }
DBUS_EXPORT long dbus_connection_free_data_slot() { return 0; }
DBUS_EXPORT long dbus_connection_set_data() { return 0; }
DBUS_EXPORT long dbus_connection_get_data() { return 0; }
DBUS_EXPORT long dbus_connection_set_change_sigpipe() { return 0; }
DBUS_EXPORT long dbus_connection_set_max_message_size() { return 0; }
DBUS_EXPORT long dbus_connection_get_max_message_size() { return 0; }
DBUS_EXPORT long dbus_connection_set_max_received_size() { return 0; }
DBUS_EXPORT long dbus_connection_get_max_received_size() { return 0; }
DBUS_EXPORT long dbus_connection_set_max_message_unix_fds() { return 0; }
DBUS_EXPORT long dbus_connection_get_max_message_unix_fds() { return 0; }
DBUS_EXPORT long dbus_connection_set_max_received_unix_fds() { return 0; }
DBUS_EXPORT long dbus_connection_get_max_received_unix_fds() { return 0; }
DBUS_EXPORT long dbus_connection_get_outgoing_size() { return 0; }
DBUS_EXPORT long dbus_connection_get_outgoing_unix_fds() { return 0; }
DBUS_EXPORT long dbus_connection_preallocate_send() { return 0; }
DBUS_EXPORT long dbus_connection_free_preallocated_send() { return 0; }
DBUS_EXPORT long dbus_connection_send_preallocated() { return 0; }
DBUS_EXPORT long dbus_connection_try_register_object_path() { return 0; }
DBUS_EXPORT long dbus_connection_register_object_path() { return 0; }
DBUS_EXPORT long dbus_connection_try_register_fallback() { return 0; }
DBUS_EXPORT long dbus_connection_register_fallback() { return 0; }
DBUS_EXPORT long dbus_connection_unregister_object_path() { return 0; }
DBUS_EXPORT long dbus_connection_get_object_path_data() { return 0; }
DBUS_EXPORT long dbus_connection_list_registered() { return 0; }
DBUS_EXPORT long dbus_connection_get_unix_fd() { return 0; }
DBUS_EXPORT long dbus_connection_get_socket() { return 0; }
DBUS_EXPORT long dbus_watch_get_fd() { return 0; }
DBUS_EXPORT long dbus_watch_get_unix_fd() { return 0; }
DBUS_EXPORT long dbus_watch_get_socket() { return 0; }
DBUS_EXPORT long dbus_watch_get_flags() { return 0; }
DBUS_EXPORT long dbus_watch_get_data() { return 0; }
DBUS_EXPORT long dbus_watch_set_data() { return 0; }
DBUS_EXPORT long dbus_watch_handle() { return 0; }
DBUS_EXPORT long dbus_watch_get_enabled() { return 0; }
DBUS_EXPORT long dbus_timeout_get_interval() { return 0; }
DBUS_EXPORT long dbus_timeout_get_data() { return 0; }
DBUS_EXPORT long dbus_timeout_set_data() { return 0; }
DBUS_EXPORT long dbus_timeout_handle() { return 0; }
DBUS_EXPORT long dbus_timeout_get_enabled() { return 0; }
DBUS_EXPORT long dbus_bus_get() { return 0; }
DBUS_EXPORT long dbus_bus_get_private() { return 0; }
DBUS_EXPORT long dbus_bus_register() { return 0; }
DBUS_EXPORT long dbus_bus_set_unique_name() { return 0; }
DBUS_EXPORT long dbus_bus_get_unique_name() { return 0; }
DBUS_EXPORT long dbus_bus_get_unix_user() { return 0; }
DBUS_EXPORT long dbus_bus_get_id() { return 0; }
DBUS_EXPORT long dbus_bus_request_name() { return 0; }
DBUS_EXPORT long dbus_bus_release_name() { return 0; }
DBUS_EXPORT long dbus_bus_name_has_owner() { return 0; }
DBUS_EXPORT long dbus_bus_start_service_by_name() { return 0; }
DBUS_EXPORT long dbus_bus_add_match() { return 0; }
DBUS_EXPORT long dbus_bus_remove_match() { return 0; }
DBUS_EXPORT long dbus_get_local_machine_id() { return 0; }
DBUS_EXPORT long dbus_get_version() { return 0; }
DBUS_EXPORT long dbus_setenv() { return 0; }
DBUS_EXPORT long dbus_try_get_local_machine_id() { return 0; }
DBUS_EXPORT long dbus_pending_call_ref() { return 0; }
DBUS_EXPORT long dbus_pending_call_unref() { return 0; }
DBUS_EXPORT long dbus_pending_call_set_notify() { return 0; }
DBUS_EXPORT long dbus_pending_call_cancel() { return 0; }
DBUS_EXPORT long dbus_pending_call_get_completed() { return 0; }
DBUS_EXPORT long dbus_pending_call_steal_reply() { return 0; }
DBUS_EXPORT long dbus_pending_call_block() { return 0; }
DBUS_EXPORT long dbus_pending_call_allocate_data_slot() { return 0; }
DBUS_EXPORT long dbus_pending_call_free_data_slot() { return 0; }
DBUS_EXPORT long dbus_pending_call_set_data() { return 0; }
DBUS_EXPORT long dbus_pending_call_get_data() { return 0; }
DBUS_EXPORT long dbus_server_listen() { return 0; }
DBUS_EXPORT long dbus_server_ref() { return 0; }
DBUS_EXPORT long dbus_server_unref() { return 0; }
DBUS_EXPORT long dbus_server_disconnect() { return 0; }
DBUS_EXPORT long dbus_server_get_is_connected() { return 0; }
DBUS_EXPORT long dbus_server_get_address() { return 0; }
DBUS_EXPORT long dbus_server_get_id() { return 0; }
DBUS_EXPORT long dbus_server_set_new_connection_function() { return 0; }
DBUS_EXPORT long dbus_server_set_watch_functions() { return 0; }
DBUS_EXPORT long dbus_server_set_timeout_functions() { return 0; }
DBUS_EXPORT long dbus_server_set_auth_mechanisms() { return 0; }
DBUS_EXPORT long dbus_server_allocate_data_slot() { return 0; }
DBUS_EXPORT long dbus_server_free_data_slot() { return 0; }
DBUS_EXPORT long dbus_server_set_data() { return 0; }
DBUS_EXPORT long dbus_server_get_data() { return 0; }
DBUS_EXPORT long dbus_signature_iter_init() { return 0; }
DBUS_EXPORT long dbus_signature_iter_get_current_type() { return 0; }
DBUS_EXPORT long dbus_signature_iter_get_signature() { return 0; }
DBUS_EXPORT long dbus_signature_iter_get_element_type() { return 0; }
DBUS_EXPORT long dbus_signature_iter_next() { return 0; }
DBUS_EXPORT long dbus_signature_iter_recurse() { return 0; }
DBUS_EXPORT long dbus_signature_validate() { return 0; }
DBUS_EXPORT long dbus_signature_validate_single() { return 0; }
DBUS_EXPORT long dbus_type_is_valid() { return 0; }
DBUS_EXPORT long dbus_type_is_basic() { return 0; }
DBUS_EXPORT long dbus_type_is_container() { return 0; }
DBUS_EXPORT long dbus_type_is_fixed() { return 0; }
DBUS_EXPORT long dbus_validate_path() { return 0; }
DBUS_EXPORT long dbus_validate_interface() { return 0; }
DBUS_EXPORT long dbus_validate_member() { return 0; }
DBUS_EXPORT long dbus_validate_error_name() { return 0; }
DBUS_EXPORT long dbus_validate_bus_name() { return 0; }
DBUS_EXPORT long dbus_validate_utf8() { return 0; }
DBUS_EXPORT long dbus_threads_init() { return 0; }
DBUS_EXPORT long dbus_threads_init_default() { return 0; }
